import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e3e2e2",
        "inverse-primary": "#775a19",
        "on-tertiary-container": "#3b3b3b",
        "primary-fixed-dim": "#e9c176",
        "on-primary-container": "#4e3700",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-container": "#a7a5a5",
        "surface-container-low": "#1b1c1c",
        "on-primary-fixed-variant": "#5d4201",
        "surface-container-highest": "#343535",
        "surface-dim": "#121414",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#1c1b1b",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#bab8b7",
        background: "#121414",
        surface: "#121414",
        "surface-variant": "#343535",
        "primary-fixed": "#ffdea5",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#474746",
        tertiary: "#c8c6c5",
        "on-background": "#e3e2e2",
        "secondary-container": "#4a4949",
        "surface-bright": "#383939",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary": "#412d00",
        "inverse-on-surface": "#2f3031",
        "outline-variant": "#4e4639",
        "on-secondary": "#313030",
        "on-surface-variant": "#d1c5b4",
        "primary-container": "#c5a059",
        "tertiary-fixed": "#e5e2e1",
        "surface-tint": "#e9c176",
        secondary: "#c8c6c5",
        primary: "#e9c176",
        error: "#ffb4ab",
        "surface-container": "#1f2020",
        "inverse-surface": "#e3e2e2",
        "on-secondary-fixed-variant": "#474646",
        outline: "#9a8f80",
        "error-container": "#93000a",
        "surface-container-high": "#292a2a",
        "on-tertiary": "#313030",
        "surface-container-lowest": "#0d0e0f",
        "on-primary-fixed": "#261900",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "section-gap": "160px",
        "stack-md": "16px",
        gutter: "24px",
      },
      fontFamily: {
        serif: ["Bodoni Moda", "serif"],
        sans: ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Bodoni Moda", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "headline-xl": ["Bodoni Moda", "serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-sm": [
          "24px",
          { lineHeight: "1.4", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "headline-xl-mobile": [
          "40px",
          { lineHeight: "1.1", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "400" },
        ],
        "headline-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
      backgroundImage: {
        "metallic-gradient":
          "linear-gradient(135deg, #e9c176 0%, #c5a059 50%, #ffdea5 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
